# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 1073741824 # 1024*2^20 bytes = 1024Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432